### ISSUE TITLE
Clear_line function not defined

### ISSUE THREAD

**Issue by KasperEinarson** [renewables-ninja/ninja_automator#1]
Hello!
Nice R code i just wonder about how the Clear_line function in line #175 is defined. When entering the function _enforce_rate_limits_ an error is thrown: "Error: could not find function "clear_line" . The clear_line function only appears at line #175 and line #179 within the  _enforce_rate_limits_ function.

**Comment by KasperEinarson** [comment]
The comment in In line 315 seems to introduce, in the following lines of code, the functions _Flush_line_ and _Clear_Line_ but only _Flush_line_ is defined

**Comment by iain-staffell** [comment]
Hi Kasper, thanks for spotting this - the function on line 316 was supposed to be clear_line().  This was fixed as of 24/09/2017 in an update by renaming the function to cat_flush()
